create or replace PROCEDURE         SP_SALESFORCEDELTA
AS
    -- Variable that holds the count of total records for this run. Used in the MAT_DELTA_SF_RUNLOG Table.
    P_SF_STAGING_COUNT NUMBER;
    -- Variable that holds last runtime from the MAT_DELTA_SF_RUNLOG Table.
    P_SF_LASTRUNDATETIME DATE;

BEGIN

EXECUTE IMMEDIATE 'DROP TABLE TBL_RPT_MAT_REPORTING';
COMMIT;

EXECUTE IMMEDIATE 'CREATE TABLE TBL_RPT_MAT_REPORTING AS SELECT * FROM RPT_MAT_REPORTING';

COMMIT;
-- Retrieve the last runtime from the runlog.
SELECT RUNTIME INTO P_SF_LASTRUNDATETIME FROM MAT_DELTA_SF_RUNLOG WHERE ID IN (SELECT MAX(ID) FROM MAT_DELTA_SF_RUNLOG);

--Step 1 : Truncate Delta Staging Table
EXECUTE IMMEDIATE 'TRUNCATE TABLE MAT_DELTA_SF_STAGING';
COMMIT;

--Step 2  : Check for Delta Logic (SEASONS.TRACK_DELTA = 'Y' and SEASONS.INITIAL_DATA_LOADED = 'Y').
--Step 2A : Delta - Adoptions (Generic is populated, Color Marketing Name is populated 
--                  and one of the adoption date fields are populated)
--          Modified Date of the field must fall between the last runlog datetime and the current run datetime
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING
(
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME,  SF_FIELDNAME,  FIELDVALUE,
  SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE, STATUS
)
WITH ADOPTIONS_GENERIC_NUM_CHECK AS -- Pull magtemplates_id and row_id where there is a generic number
(
    SELECT A.magtemplates_id, A.row_id 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
    AND (A.FIELDS_ID = 6 AND a.fieldvalue IS NOT NULL)
),
ADOPTIONS_CMN_FIELDS_CHECK AS -- Pull magtemplates_id and row_id where color code and flex style number is not null
(
    SELECT A.magtemplates_id, A.row_id, A.fieldvalue as ZZ_PLMID, B.fieldvalue as ZZ_CHOICEID, C.SEASON_YEAR as FLEX_YEAR, C.SEASON_NAME as FLEX_SEASON
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    INNER JOIN MAT B ON B.magtemplates_id = A.MAGTEMPLATES_ID AND B.row_id = A.row_id
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
      AND (A.FIELDS_ID = 1 AND A.fieldvalue IS NOT NULL)
      AND (B.FIELDS_ID = 2 AND B.fieldvalue IS NOT NULL)
),
ADOPTIONS_CMN_CHECK AS
(
    SELECT A.magtemplates_id, A.row_id
    FROM ADOPTIONS_CMN_FIELDS_CHECK A
    INNER JOIN mpa_master.flex_stylecolors B 
        ON A.ZZ_PLMID = B.ZZ_PLMID 
        AND A.ZZ_CHOICEID = B.ZZ_CHOICEID
        AND A.FLEX_YEAR = B.FLEX_YEAR
        AND A.FLEX_SEASON = B.FLEX_SEASON
),
ADOPTIONS_DATE_CHECK AS -- Pull magtemplates_id and row_id where at least one of the following dates exist
                        -- Stores (184), Digital (185), International (186) Adoption Time Stamp
(
    SELECT A.magtemplates_id, A.row_id 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
    AND (A.FIELDS_ID in (184,185,186) AND A.fieldvalue IS NOT NULL)
    GROUP BY A.magtemplates_id, A.row_id
),
ADOPTIONS_RESULTS AS -- Pull magtemplates_id and row_id where there is a generic number and a color marketing name
(
    SELECT A.magtemplates_id, A.row_id 
    FROM ADOPTIONS_GENERIC_NUM_CHECK A
    INNER JOIN ADOPTIONS_CMN_CHECK B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.row_id = B.row_id
    INNER JOIN ADOPTIONS_DATE_CHECK C ON A.MAGTEMPLATES_ID = C.MAGTEMPLATES_ID AND A.row_id = C.row_id
)
SELECT C.MAG_ID,C.MAG_NAME, A.MAGTEMPLATES_ID, C.TEMPLATES_NAME, 
    A.ROW_ID, C.BRAND_ID, C.BRAND_NAME, C.SEASONS_ID, 
    C.SEASON_YEAR, C.SEASON_NAME, C.SEASON_SHORTNAME, B.SALESFORCE_NAME, A.FIELDVALUE, 
    B.SORT_ORDER,A.MAGTEMPLATES_ID,A.CREATE_DATE,A.MODIFIED_DATE,'N' 
FROM MAT A 
INNER JOIN MAT_DELTA_SF_FIELDS B ON A.FIELDS_ID = B.FIELDS_ID
INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
INNER JOIN ADOPTIONS_RESULTS D ON d.magtemplates_id = A.MAGTEMPLATES_ID and d.row_id = a.row_id 
WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND A.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

-- 2A.1 : Ensure that all rows have a Planning Choice record, if one exists.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING
(
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME,  SF_FIELDNAME,  FIELDVALUE,
  SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE, STATUS
)
WITH STAGING_ROWS_WO_PC AS
(-- 1 - Pull all distinct rows from mat staging that do not have a planning choice record
SELECT distinct A.magtemplates_id, A.row_id 
FROM mat_delta_sf_staging A
INNER JOIN MDIS_MAGTEMPLATES B ON B.ID = A.MAGTEMPLATES_ID
WHERE B.SEASONS_ID IN (SELECT C.ID FROM SEASONS C WHERE C.TRACK_DELTA = 'Y' AND C.INITIAL_DATA_LOADED = 'Y')
and (a.magtemplates_id || a.row_id) not in (select D.magtemplates_id || D.row_id 
                                            from mat_delta_sf_staging D 
                                            where D.sf_fieldname = 'Planning_Choice__c' 
                                            and D.fieldvalue is not null)
), PC_FROM_MAT AS
(
SELECT E.magtemplates_id, E.row_id, E.fieldvalue
FROM MAT E
WHERE (E.MAGTEMPLATES_ID || E.ROW_ID) IN (select F.MAGTEMPLATES_ID || F.ROW_ID from staging_rows_wo_pc F)
AND E.FIELDS_ID = 3 -- Planning Choice
)
SELECT distinct B.MAG_ID,B.MAG_NAME, A.MAGTEMPLATES_ID, B.TEMPLATES_NAME, 
    A.ROW_ID, B.BRAND_ID, B.BRAND_NAME, B.SEASONS_ID, 
    B.SEASON_YEAR, B.SEASON_NAME, B.SEASON_SHORTNAME, 'Planning_Choice__c', D.FIELDVALUE, 
    137,A.MAGTEMPLATES_ID,A.CREATE_DATE,A.MODIFIED_DATE,'N' 
FROM mat_delta_sf_staging A 
INNER JOIN MDIS_MAGTEMPLATES B ON B.ID = A.MAGTEMPLATES_ID
INNER JOIN PC_FROM_MAT D ON D.magtemplates_id = A.MAGTEMPLATES_ID and D.row_id = A.row_id AND D.fieldvalue is not null
WHERE B.SEASONS_ID IN (SELECT D.ID FROM SEASONS D WHERE D.TRACK_DELTA = 'Y' AND D.INITIAL_DATA_LOADED = 'Y')
AND A.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

--Step 3  : Check for Initial Load Logic (SEASONS.TRACK_DELTA = 'Y' and SEASONS.INITIAL_DATA_LOADED = 'N')
--Step 3A : Initial Load - Adoptions (Generic is populated, Color Marketing Name is populated 
--                         and one of the adoption date fields are populated)
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING
(
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,  FIELDVALUE,
  SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,STATUS
)
WITH ADOPTIONS_GENERIC_NUM_CHECK AS -- Pull magtemplates_id and row_id where there is a generic number
(
    SELECT A.magtemplates_id, A.row_id 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N')
    AND (A.FIELDS_ID = 6 AND a.fieldvalue IS NOT NULL)
),
ADOPTIONS_CMN_CHECK AS -- Pull magtemplates_id and row_id where there is a color marketing name
(
    SELECT DISTINCT A.MAGTEMPLATES_ID, A.ROW_ID
    FROM TBL_RPT_MAT_REPORTING A WHERE A.SEASON_SHORTNAME IN (SELECT SHORTNAME FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N')
    AND A.COLOR_MARKETING_NAME IS NOT NULL
), 
ADOPTIONS_DATE_CHECK AS -- Pull magtemplates_id and row_id where at least one of the following dates exist
                        -- Stores (184), Digital (185), International (186) Adoption Time Stamp
                        -- Pull all fields
(
    SELECT A.magtemplates_id, A.row_id 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N')
    AND (A.FIELDS_ID in (184,185,186) AND A.fieldvalue IS NOT NULL)
    GROUP BY A.magtemplates_id, A.row_id
),
ADOPTIONS_RESULTS AS -- Pull magtemplates_id and row_id where there is a generic number and a color marketing name
(
    SELECT A.magtemplates_id, A.row_id 
    FROM ADOPTIONS_GENERIC_NUM_CHECK A
    INNER JOIN ADOPTIONS_CMN_CHECK B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.row_id = B.row_id
    INNER JOIN ADOPTIONS_DATE_CHECK C ON A.MAGTEMPLATES_ID = C.MAGTEMPLATES_ID AND A.row_id = C.row_id
)
SELECT C.MAG_ID,C.MAG_NAME, A.MAGTEMPLATES_ID, C.TEMPLATES_NAME, 
    A.ROW_ID, C.BRAND_ID, C.BRAND_NAME, C.SEASONS_ID, 
    C.SEASON_YEAR, C.SEASON_NAME, C.SEASON_SHORTNAME, B.SALESFORCE_NAME, A.FIELDVALUE, 
    B.SORT_ORDER,A.MAGTEMPLATES_ID,A.CREATE_DATE,A.MODIFIED_DATE,'N' 
FROM MAT A 
INNER JOIN MAT_DELTA_SF_FIELDS B ON A.FIELDS_ID = B.FIELDS_ID
INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
INNER JOIN ADOPTIONS_RESULTS D ON d.magtemplates_id = A.MAGTEMPLATES_ID and d.row_id = a.row_id 
WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

--Step 3B : Initial Load - Generics (Generic is populated, Color Marketing Name is NOT populated) -- Do we need this?
--                  Pull Style Related Fields Only
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING
(
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME,  SF_FIELDNAME,  FIELDVALUE,
  SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,STATUS
)
WITH GENERICS_GENERIC_NUM_CHECK AS -- Pull magtemplates_id and row_id where there is a generic number
(
    SELECT A.magtemplates_id, A.row_id 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N')
    AND (A.FIELDS_ID = 6 AND a.fieldvalue IS NOT NULL)
),
GENERICS_CMN_FIELDS_CHECK AS -- Pull magtemplates_id and row_id where color marketing name is populated
                             -- We will LEFT JOIN with the magtemplates/rows that have generic number
                             -- in GENERIC_RESULTS so that we only have magtemplates/rows that have a 
                             -- generic number populated but do not have a color marketing name.
(
    SELECT A.magtemplates_id, A.row_id, A.fieldvalue as ZZ_PLMID, B.fieldvalue as ZZ_CHOICEID, C.SEASON_YEAR as FLEX_YEAR, C.SEASON_NAME as FLEX_SEASON
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
    INNER JOIN MAT B ON B.magtemplates_id = A.MAGTEMPLATES_ID AND B.row_id = A.row_id
    WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N')
      AND (A.FIELDS_ID = 1 AND A.fieldvalue IS NOT NULL)
      AND (B.FIELDS_ID = 2 AND B.fieldvalue IS NOT NULL)
),
GENERICS_CMN_CHECK AS
(
    SELECT A.magtemplates_id, A.row_id
    FROM GENERICS_CMN_FIELDS_CHECK A
    INNER JOIN mpa_master.flex_stylecolors B 
        ON A.ZZ_PLMID = B.ZZ_PLMID 
        AND A.ZZ_CHOICEID = B.ZZ_CHOICEID
        AND A.FLEX_YEAR = B.FLEX_YEAR
        AND A.FLEX_SEASON = B.FLEX_SEASON
),
GENERICS_RESULTS AS -- Pull magtemplates_id and row_id where there is a generic number and no color marketing name
(
    SELECT A.magtemplates_id, A.row_id
    FROM GENERICS_GENERIC_NUM_CHECK A
    LEFT JOIN GENERICS_CMN_CHECK B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
    WHERE (B.MAGTEMPLATES_ID IS NULL AND B.ROW_ID IS NULL)
)
SELECT C.MAG_ID,C.MAG_NAME, A.MAGTEMPLATES_ID, C.TEMPLATES_NAME, 
    A.ROW_ID, C.BRAND_ID, C.BRAND_NAME, C.SEASONS_ID, 
    C.SEASON_YEAR, C.SEASON_NAME, C.SEASON_SHORTNAME, B.SALESFORCE_NAME, A.FIELDVALUE, 
    B.SORT_ORDER,A.MAGTEMPLATES_ID,A.CREATE_DATE,A.MODIFIED_DATE,'N' 
FROM MAT A 
INNER JOIN MAT_DELTA_SF_FIELDS B ON A.FIELDS_ID = B.FIELDS_ID AND B.STYLE_LEVEL = 'Y'
INNER JOIN MDIS_MAGTEMPLATES C ON C.ID = A.MAGTEMPLATES_ID
INNER JOIN GENERICS_RESULTS D ON d.magtemplates_id = A.MAGTEMPLATES_ID and d.row_id = a.row_id 
WHERE C.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

--Step 4 : Insert Fiber Content fields using Planning Choice
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH MATARTICLE AS
(
    SELECT /*+ parallel(B,4) */ MAX(B.MATNR) ARTICLE, A.FIELDVALUE ZZ_CHOICEID,
        A.MAG_ID,A.MAG_NAME,A.MAGTEMPLATES_ID,A.MAGTEMPLATES_NAME,A.ROW_ID,A.BRAND_ID,A.BRAND_NAME,A.SEASONS_ID,A.SEASON_YEAR,
        A.SEASON_NAME,A.SEASON_SHORTNAME,A.SORT_ORDER,A.CREATE_DATE,A.MODIFIED_DATE
    FROM MAT_DELTA_SF_STAGING A INNER JOIN MPA_MASTER.SAP_MARA B 
    ON A.FIELDVALUE = TRIM(B.ZZ_CHOICEID)
    WHERE A.SF_FIELDNAME = 'Planning_Choice__c' AND A.FIELDVALUE IS NOT NULL
    GROUP BY    A.MAG_ID,A.MAG_NAME,A.MAGTEMPLATES_ID,A.MAGTEMPLATES_NAME,A.ROW_ID,A.BRAND_ID,A.BRAND_NAME,A.SEASONS_ID,
                A.SEASON_YEAR,A.SEASON_NAME,A.SEASON_SHORTNAME,A.FIELDVALUE,A.SORT_ORDER,A.CREATE_DATE,A.MODIFIED_DATE
),
DISTARTICLE AS
(
    SELECT DISTINCT ARTICLE FROM MATARTICLE
),
RESULTS AS
(
    SELECT /*+ MATERIALIZE*/ * FROM MPA_MASTER.SAP_ESTDF ESTDF WHERE TEXTCAT = 'Z_INT_FB_P'
),
FIBER_DATE AS 
(
    SELECT * FROM 
    (
        SELECT /*+ parallel(ESTVA,8) */ ESTMJ.UPDDAT, DBMS_LOB.SUBSTR(ESTDF.HEADER, 1000, 1 ) AS FIELD_VALUE, ESTMJ.MATNR AS ARTICLE,
        DENSE_RANK() OVER (PARTITION BY ESTMJ.MATNR ORDER BY ROWNUM) DENSE_RANK
        FROM RESULTS ESTDF
        INNER JOIN MPA_MASTER.SAP_AUSP_EHS AUSP ON SUBSTR(AUSP.OBJEK,0,20) = ESTDF.RECNMST
        INNER JOIN MPA_MASTER.SAP_ESTVA ESTVA ON SUBSTR(AUSP.OBJEK,0,20) = ESTVA.RECN
        INNER JOIN MPA_MASTER.SAP_ESTVH ESTVH ON ESTVH.RECN = ESTVA.RECNTVH
        INNER JOIN MPA_MASTER.SAP_ESTMJ ESTMJ ON ESTMJ.RECNROOT = ESTVH.RECNROOT 
        WHERE TEXTCAT = 'Z_INT_FB_P'
        AND AUSP.ATINN = 'Z_INT_LANG' 
        AND AUSP.ATWRT = 'EN'
        AND EXISTS (SELECT ARTICLE FROM DISTARTICLE DA WHERE DA.ARTICLE = ESTMJ.MATNR)
        ORDER BY  ESTMJ.MATNR
    ) WHERE DENSE_RANK = 1
)
SELECT MATD.MAG_ID,  MATD.MAG_NAME,  MATD.MAGTEMPLATES_ID,  MATD.MAGTEMPLATES_NAME,
  MATD.ROW_ID,  MATD.BRAND_ID,  MATD.BRAND_NAME,  MATD.SEASONS_ID,
  MATD.SEASON_YEAR,  MATD.SEASON_NAME, MATD.SEASON_SHORTNAME,'Fiber_Content__c', FIBER.FIELD_VALUE,
  263, MATD.MAGTEMPLATES_ID,MATD.CREATE_DATE,MATD.MODIFIED_DATE,'N'
FROM MATARTICLE MATD INNER JOIN FIBER_DATE FIBER ON MATD.ARTICLE = FIBER.ARTICLE;
COMMIT;

--Step 5 : Insert Master Style Description from the reporting view based on Planning Choice
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT STG.MAG_ID,  STG.MAG_NAME,  STG.MAGTEMPLATES_ID,  STG.MAGTEMPLATES_NAME,
  STG.ROW_ID,  STG.BRAND_ID,  STG.BRAND_NAME,  STG.SEASONS_ID,
  STG.SEASON_YEAR,  STG.SEASON_NAME, STG.SEASON_SHORTNAME,'Master_Style_Desc__c', RPT.masterstyle_desc,
  118, STG.MAGTEMPLATES_ID,STG.CREATE_DATE,STG.MODIFIED_DATE,'N'
FROM mat_delta_sf_staging STG, TBL_RPT_MAT_REPORTING RPT
WHERE STG.sf_fieldname = 'Planning_Choice__c'
AND RPT.masterstyle_desc IS NOT NULL
AND STG.fieldvalue = trim(RPT.planning_choice)
AND RPT.FLEX_YEAR = STG.SEASON_YEAR
AND RPT.FLEX_SEASON = STG.SEASON_NAME;
COMMIT;

--Step 6 : Insert Generic Description from the reporting view based on Planning Choice
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT STG.MAG_ID,  STG.MAG_NAME,  STG.MAGTEMPLATES_ID,  STG.MAGTEMPLATES_NAME,
  STG.ROW_ID,  STG.BRAND_ID,  STG.BRAND_NAME,  STG.SEASONS_ID,
  STG.SEASON_YEAR,  STG.SEASON_NAME, STG.SEASON_SHORTNAME,'Generic_Description__c', RPT.generic_desc,
  264, STG.MAGTEMPLATES_ID,STG.CREATE_DATE,STG.MODIFIED_DATE,'N'
FROM mat_delta_sf_staging STG, TBL_RPT_MAT_REPORTING RPT
WHERE STG.sf_fieldname = 'Planning_Choice__c'
AND RPT.generic_desc IS NOT NULL
AND STG.fieldvalue = trim(RPT.planning_choice)
AND RPT.FLEX_YEAR = STG.SEASON_YEAR
AND RPT.FLEX_SEASON = STG.SEASON_NAME;
COMMIT;

--Added by Senthilkumar Bose Step 6.1 : Adding Unique value column (NAME  = MAGTEMPLATES_ID || FIELDVALUE  -- Planning Choice)
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'Name' AS SF_FIELDNAME, (MAGTEMPLATES_ID || FIELDVALUE) AS FIELDVALUE, 
999 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 7 : If this is an initial load for a season (SEASONS.TRACK_DELTA = 'Y' and SEASONS.INITIAL_DATA_LOADED = 'N')
--         Set the NEW_ADD_DELETE flag in the Staging table for all Planning Choice records (Adoptions) to 'N' (New) 
MERGE INTO mat_delta_sf_staging target
USING (SELECT A.*
FROM mat_delta_sf_staging A
INNER JOIN seasons B
ON A.season_year = B.year AND A.season_name = B.name
WHERE A.sf_fieldname = 'Planning_Choice__c'
AND B.track_delta = 'Y' AND B.initial_data_loaded = 'N') source
ON
(target.magtemplates_id = source.magtemplates_id
AND target.row_id = source.row_id
AND target.sf_fieldname = source.sf_fieldname)
WHEN MATCHED THEN
UPDATE SET target.new_add_delete = 'N';
COMMIT;

-- Insert records into the MAT_DELTA_SF_ADOPTIONS table
INSERT /*+ append  */ INTO MAT_DELTA_SF_ADOPTIONS (
  MAGTEMPLATES_ID,
  PLANNING_CHOICE,
  DATE_CREATED
)
SELECT a.magtemplates_id, a.fieldvalue,SYSDATE
FROM mat_delta_sf_staging A
INNER JOIN seasons B
ON A.season_year = B.year AND A.season_name = B.name
WHERE A.sf_fieldname = 'Planning_Choice__c'
AND b.track_delta = 'Y' AND b.initial_data_loaded = 'N';
COMMIT;

--Step 8 : If a mat_delta_sf_staging.magtemplates_id does not exist in mat_delta_sf_adoptions
--         and mat_delta_sf_staging.new_add_delete flag has not been populated
--         then we know this is a new MAT workbook, not an initial load (because the new_add_delete flag
--         was populated for initial loading above), and that all of the planning choices associated
--         with this MAT should be set to new.

MERGE INTO mat_delta_sf_staging target
USING (SELECT A.*
FROM mat_delta_sf_staging A
LEFT JOIN mat_delta_sf_adoptions B
ON A.magtemplates_id = B.magtemplates_id
WHERE B.magtemplates_id IS NULL
AND A.sf_fieldname = 'Planning_Choice__c'
AND A.new_add_delete IS NULL) source
ON 
(target.magtemplates_id = source.magtemplates_id
AND target.row_id = source.row_id
AND target.sf_fieldname = source.sf_fieldname)
WHEN MATCHED THEN
UPDATE SET target.new_add_delete = 'N';
COMMIT;

-- Insert records into the MAT_DELTA_SF_ADOPTIONS table
INSERT /*+ append  */ INTO MAT_DELTA_SF_ADOPTIONS (
  MAGTEMPLATES_ID,
  PLANNING_CHOICE,
  DATE_CREATED
)
SELECT a.magtemplates_id, a.fieldvalue,SYSDATE
FROM mat_delta_sf_staging A
LEFT JOIN mat_delta_sf_adoptions B
ON A.magtemplates_id = B.magtemplates_id
WHERE B.magtemplates_id IS NULL
AND A.sf_fieldname = 'Planning_Choice__c'
AND A.new_add_delete IS NULL;
COMMIT;

--Step 9 : If the mat_delta_sf_staging.magtemplates_id/Planning Choice combination does not exist
--         in mat_delta_sf_adoptions and mat_delta_sf_staging.new_add_delete flag has not been populated
--         (because the new_add_delete flag was populated for initial loading or because it was a 
--          new MAT workbook during the delta process)
--         Planning Choice records should be set to 'Add'
MERGE INTO mat_delta_sf_staging target
USING (SELECT A.*
FROM mat_delta_sf_staging A
LEFT JOIN mat_delta_sf_adoptions B
ON A.magtemplates_id = B.magtemplates_id AND A.fieldvalue = B.planning_choice
WHERE B.magtemplates_id IS NULL
AND A.sf_fieldname = 'Planning_Choice__c'
AND A.new_add_delete IS NULL) source
ON 
(target.magtemplates_id = source.magtemplates_id
AND target.row_id = source.row_id
AND target.sf_fieldname = source.sf_fieldname)
WHEN MATCHED THEN
UPDATE SET target.new_add_delete = 'A';
COMMIT;

-- Insert records into the MAT_DELTA_SF_ADOPTIONS table
INSERT /*+ append  */ INTO MAT_DELTA_SF_ADOPTIONS (
  MAGTEMPLATES_ID,
  PLANNING_CHOICE,
  DATE_CREATED
)
SELECT A.magtemplates_id, A.fieldvalue,SYSDATE
FROM mat_delta_sf_staging A
LEFT JOIN mat_delta_sf_adoptions B
ON A.magtemplates_id = B.magtemplates_id AND A.fieldvalue = B.planning_choice
WHERE B.magtemplates_id IS NULL
AND A.sf_fieldname = 'Planning_Choice__c'
AND A.new_add_delete IS NULL;
COMMIT;

--Step 10 : If the mat_delta_sf_adoptions.magtemplates_id/Planning Choice combination does not exist
--          in the main MAT table, this means that the row that contains this planning choice has
--          been deleted.

-- Insert a planning choice records into mat_delta_sf_staging designating that they are deleted
-- (mat_delta_sf_staging.new_add_delete = 'D')
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID, SEASON_YEAR,  SEASON_NAME, 
  SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,
  CREATE_DATE,MODIFIED_DATE, NEW_ADD_DELETE
)
WITH MAT_MT_PC AS -- Pull magtemplates_id and planning choice records from MAT where we are tracking the season
(
    SELECT A.magtemplates_id AS MAT_MT_ID, A.fieldvalue as MAT_PLANNING_CHOICE 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES B ON B.ID = A.MAGTEMPLATES_ID
    WHERE B.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y')
    AND A.FIELDS_ID = 3
),
MT_PC_IN_ADOPTIONS_NOT_MAT AS -- Select mat_delta_sf_adoptions records that are not in the MAT table
(
    SELECT *
    FROM mat_delta_sf_adoptions A
    LEFT JOIN MAT_MT_PC B
    ON A.magtemplates_id = B.MAT_MT_ID AND A.planning_choice = B.MAT_PLANNING_CHOICE
    WHERE B.MAT_MT_ID IS NULL and B.MAT_PLANNING_CHOICE IS NULL
)
SELECT 999999 AS MAG_ID, 'MAG_DELETE' AS MAG_NAME, MAGTEMPLATES_ID, 
        'MAGTEMPLATES_DELETE' AS MAGTEMPLATES_NAME,  999999 AS ROW_ID,  
        999999 AS BRAND_ID, 'BRAND_DELETE' AS BRAND_NAME, 999999 AS SEASONS_ID, 
        '9999' AS SEASON_YEAR, 'SEASON_DELETE' AS SEASON_NAME, 
        '9999' AS SEASON_SHORTNAME, 'Planning_Choice__c' AS FIELDNAME, PLANNING_CHOICE AS FIELDVALUE, 
        137 AS SORT_ORDER, MAGTEMPLATES_ID AS SEGMENT_COUNT,
        TO_CHAR(SYSDATE, 'DD-MON-YYYY HH24:MI:SS') AS CREATE_DATE, 
        TO_CHAR(SYSDATE, 'DD-MON-YYYY HH24:MI:SS') AS MODIFIED_DATE, 'D'
FROM MT_PC_IN_ADOPTIONS_NOT_MAT
COMMIT;

--Delete the records from the mat_delta_sf_adoptions table because they no longer exist in MAT
DELETE FROM mat_delta_sf_adoptions 
WHERE magtemplates_id in
(WITH MAT_MT_PC AS -- Pull magtemplates_id and planning choice records from MAT where we are tracking the season
(
    SELECT A.magtemplates_id AS MAT_MT_ID, A.fieldvalue as MAT_PLANNING_CHOICE 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES B ON B.ID = A.MAGTEMPLATES_ID
    WHERE B.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y')
    AND A.FIELDS_ID = 3
),
MT_PC_IN_ADOPTIONS_NOT_MAT AS -- Select mat_delta_sf_adoptions records that are not in the MAT table
(
    SELECT *
    FROM mat_delta_sf_adoptions A
    LEFT JOIN MAT_MT_PC B
    ON A.magtemplates_id = B.MAT_MT_ID AND A.planning_choice = B.MAT_PLANNING_CHOICE
    WHERE B.MAT_MT_ID IS NULL and B.MAT_PLANNING_CHOICE IS NULL
)
SELECT magtemplates_id FROM MT_PC_IN_ADOPTIONS_NOT_MAT)
AND
planning_choice in 
(WITH MAT_MT_PC AS -- Pull magtemplates_id and planning choice records from MAT where we are tracking the season
(
    SELECT A.magtemplates_id AS MAT_MT_ID, A.fieldvalue as MAT_PLANNING_CHOICE 
    FROM MAT A
    INNER JOIN MDIS_MAGTEMPLATES B ON B.ID = A.MAGTEMPLATES_ID
    WHERE B.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y')
    AND A.FIELDS_ID = 3
),
MT_PC_IN_ADOPTIONS_NOT_MAT AS -- Select mat_delta_sf_adoptions records that are not in the MAT table
(
    SELECT *
    FROM mat_delta_sf_adoptions A
    LEFT JOIN MAT_MT_PC B
    ON A.magtemplates_id = B.MAT_MT_ID AND A.planning_choice = B.MAT_PLANNING_CHOICE
    WHERE B.MAT_MT_ID IS NULL and B.MAT_PLANNING_CHOICE IS NULL
)
SELECT planning_choice FROM MT_PC_IN_ADOPTIONS_NOT_MAT);
COMMIT;

--Step 11 : Delete all rows that do not have a Planning_Choice__c (Name) records.  We have to do this because in Step 6.1
--          Planning_Choice__c field value must exist to create the unique key (magtemplates_id/row_id/Planning Choice)
--          that Salesforce needs
DELETE FROM mat_delta_sf_staging a
where a.magtemplates_id || a.row_id not in 
(WITH MAGTEMP_ROWID_W_NAME AS -- MAGTEMPATES_ID/ROW_ID with a Name record in its recordset.
(
    SELECT magtemplates_id || row_id magtemp_row_combo 
    FROM mat_delta_sf_staging  WHERE sf_fieldname = 'Name' AND fieldvalue IS NOT NULL
    order by magtemplates_id, row_id
)
select magtemp_row_combo from magtemp_rowid_w_name);
COMMIT;

--Step 12 : Add a MAG_NAME record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'MAG_Name__c' AS SF_FIELDNAME, MAG_NAME AS FIELDVALUE, 998 AS SORT_ORDER, 
SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 13 : Add a SEASON_SHORTNAME record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'SEASON_SHORTNAME__c' AS SF_FIELDNAME, SEASON_SHORTNAME AS FIELDVALUE, 
997 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 14 : Add a SEASON_YEAR record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'Season_Year__c' AS SF_FIELDNAME, SEASON_YEAR AS FIELDVALUE, 996 AS SORT_ORDER, 
SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 15 : Add a SEASON_NAME record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'Season_Name__c' AS SF_FIELDNAME, SEASON_NAME AS FIELDVALUE, 995 AS SORT_ORDER, 
SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 15.1 : Add a BRAND record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Brand__c' AS SF_FIELDNAME, B.NAME AS FIELDVALUE, 991 AS SORT_ORDER, 
A.SEGMENT_COUNT, A.CREATE_DATE, A.MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN BRANDS B on B.id = A.brand_id
WHERE A.SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 15.2 : Add a MAGTEMPLATES_ID record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'Magtemplates_Id__c' AS SF_FIELDNAME, MAGTEMPLATES_ID AS FIELDVALUE, 990 AS SORT_ORDER, 
SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

--Step 15.3 : Add a ROW_ID record to every recordset.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
SELECT MAG_ID, MAG_NAME, MAGTEMPLATES_ID, MAGTEMPLATES_NAME, 
ROW_ID, BRAND_ID, BRAND_NAME, SEASONS_ID, 
SEASON_YEAR, SEASON_NAME, SEASON_SHORTNAME, 'Row_Id__c' AS SF_FIELDNAME, ROW_ID AS FIELDVALUE, 989 AS SORT_ORDER, 
SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING WHERE SF_FIELDNAME = 'Planning_Choice__c';
COMMIT;

-----------------------------------------------------------
-- Step 16 : Trigger Fields

-- Step 16.1 : SHARED_UNIQUE

-- Delta SHARED_UNIQUE
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH SHARED_UNIQUE_VAL AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, SHARED_UNIQUE  FROM  TBL_RPT_MAT_REPORTING
)
,
SHARED_UNIQUE_MAXDATE AS
(
    SELECT MAGTEMPLATES_ID, ROW_ID, MAX(MODIFIED_DATE) AS MODIFIED_DATE, MAX(SHARED_UNIQUE) AS SHARED_UNIQUE  FROM (
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.SHARED_UNIQUE  FROM MAT M INNER JOIN SHARED_UNIQUE_VAL S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 56
    UNION ALL
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.SHARED_UNIQUE FROM MAT M INNER JOIN SHARED_UNIQUE_VAL S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 57
    UNION ALL
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.SHARED_UNIQUE FROM MAT M INNER JOIN SHARED_UNIQUE_VAL S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 495)
    GROUP BY MAGTEMPLATES_ID, ROW_ID
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME,
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID,
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Shared_Unique__c' AS SF_FIELDNAME,  B.SHARED_UNIQUE AS FIELDVALUE, 
994 AS SORT_ORDER, A.SEGMENT_COUNT, A.CREATE_DATE, A.MODIFIED_DATE,'N'
FROM MAT_DELTA_SF_STAGING A INNER JOIN SHARED_UNIQUE_MAXDATE B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND A.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

---Intial Load SHARED_UNIQUE
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH SHARED_UNIQUE_INIT AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, SHARED_UNIQUE  FROM  TBL_RPT_MAT_REPORTING WHERE SHARED_UNIQUE IS NOT NULL
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Shared_Unique__c' AS SF_FIELDNAME,  B.SHARED_UNIQUE AS FIELDVALUE, 
994 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN SHARED_UNIQUE_INIT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

-- Step 16.2 : CATEGORY_DESC
---Delta CATEGORY_DESC
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH SAPCATEGORYDESC_UNIQUE AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, CATEGORY_DESC  FROM  TBL_RPT_MAT_REPORTING WHERE CATEGORY_DESC IS NOT NULL
)
,
SAPCATEGORYDESC_UNIQUE_DATE AS
(
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.CATEGORY_DESC  FROM MAT M INNER JOIN SAPCATEGORYDESC_UNIQUE S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 69
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME,
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID,
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'SAP_Category_Desc__c' AS SF_FIELDNAME,  B.CATEGORY_DESC AS FIELDVALUE, 
993 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, B.MODIFIED_DATE,'N'
FROM MAT_DELTA_SF_STAGING A INNER JOIN SAPCATEGORYDESC_UNIQUE_DATE B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND B.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

---Intial Load CATEGORY_DESC
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH SAPCATEGORYDESC_UNIQUE_INIT AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, CATEGORY_DESC  FROM  TBL_RPT_MAT_REPORTING WHERE CATEGORY_DESC IS NOT NULL 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'SAP_Category_Desc__c' AS SF_FIELDNAME,  B.CATEGORY_DESC AS FIELDVALUE, 
993 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN SAPCATEGORYDESC_UNIQUE_INIT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

-- Step 16.3 : COLOR_MARKETING_NAME
---Delta COLOR_MARKETING_NAME
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH COLORMARKETTINGNAME_UNIQUE AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, COLOR_MARKETING_NAME  FROM  TBL_RPT_MAT_REPORTING WHERE COLOR_MARKETING_NAME IS NOT NULL 
),
COLORMARKETTINGNAME_UNIQUEDATE AS
(
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.COLOR_MARKETING_NAME  FROM MAT M INNER JOIN COLORMARKETTINGNAME_UNIQUE S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID 
    WHERE M.FIELDS_ID = 404 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Flex_Color_Marketing_Name__c' AS SF_FIELDNAME,  
B.COLOR_MARKETING_NAME AS FIELDVALUE, 992 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, B.MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN COLORMARKETTINGNAME_UNIQUEDATE B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND B.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

---Intial Load COLOR_MARKETING_NAME
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH COLORMARKETTINGNAME_UNIQUE_INI AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, COLOR_MARKETING_NAME  FROM  TBL_RPT_MAT_REPORTING WHERE COLOR_MARKETING_NAME IS NOT NULL 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Flex_Color_Marketing_Name__c' AS SF_FIELDNAME,  
B.COLOR_MARKETING_NAME AS FIELDVALUE, 992 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN COLORMARKETTINGNAME_UNIQUE_INI B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

-- Step 16.3 : Stores Color Size Run
--INITIAL
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH STORECOLORSIZERUN_INIT AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, STORE_COLORWAY_SIZE_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE STORE_COLORWAY_SIZE_RUN IS NOT NULL 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Stores_Color_Size_Run__c' AS SF_FIELDNAME,  B.STORE_COLORWAY_SIZE_RUN AS FIELDVALUE, 
194 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN STORECOLORSIZERUN_INIT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

--DELTA
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH STORECOLORSIZERUN AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, STORE_COLORWAY_SIZE_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE STORE_COLORWAY_SIZE_RUN IS NOT NULL
)
,
STORECOLORSIZERUN_JOIN_MAT AS
(
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.STORE_COLORWAY_SIZE_RUN  
    FROM MAT M INNER JOIN STORECOLORSIZERUN S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 130
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME,
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID,
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Stores_Color_Size_Run__c' AS SF_FIELDNAME,  B.STORE_COLORWAY_SIZE_RUN AS FIELDVALUE, 
194 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, B.MODIFIED_DATE,'N'
FROM MAT_DELTA_SF_STAGING A INNER JOIN STORECOLORSIZERUN_JOIN_MAT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND B.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

-- Step 16.4 : Digital Color Size Run
--INITIAL
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH DIGITALCOLORSIZERUN_INIT AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, DIGITAL_CLR_SZ_PROF_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE DIGITAL_CLR_SZ_PROF_RUN IS NOT NULL 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Digital_Color_Size_Run__c' AS SF_FIELDNAME,  B.DIGITAL_CLR_SZ_PROF_RUN AS FIELDVALUE, 
51 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN DIGITALCOLORSIZERUN_INIT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

--DELTA
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH DIGITALCOLORSIZERUN AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, DIGITAL_CLR_SZ_PROF_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE DIGITAL_CLR_SZ_PROF_RUN IS NOT NULL
)
,
DIGITALCOLORSIZERUN_JOIN_MAT AS
(
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.DIGITAL_CLR_SZ_PROF_RUN  
    FROM MAT M INNER JOIN DIGITALCOLORSIZERUN S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 130
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME,
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID,
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'Digital_Color_Size_Run__c' AS SF_FIELDNAME,  B.DIGITAL_CLR_SZ_PROF_RUN AS FIELDVALUE, 
51 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, B.MODIFIED_DATE,'N'
FROM MAT_DELTA_SF_STAGING A INNER JOIN DIGITALCOLORSIZERUN_JOIN_MAT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND B.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

-- Step 16.5 : SEA Color Size Run
--INITIAL
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH SEACOLORSIZERUN_INIT AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, SEA_SIZE_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE SEA_SIZE_RUN IS NOT NULL 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'SEA_Size_Run__c' AS SF_FIELDNAME,  B.SEA_SIZE_RUN AS FIELDVALUE, 
151 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN SEACOLORSIZERUN_INIT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

--DELTA
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH SEACOLORSIZERUN AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, SEA_SIZE_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE SEA_SIZE_RUN IS NOT NULL
)
,
SEACOLORSIZERUN_JOIN_MAT AS
(
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.SEA_SIZE_RUN  
    FROM MAT M INNER JOIN SEACOLORSIZERUN S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 130
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME,
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID,
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'SEA_Size_Run__c' AS SF_FIELDNAME,  B.SEA_SIZE_RUN AS FIELDVALUE, 
151 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, B.MODIFIED_DATE,'N'
FROM MAT_DELTA_SF_STAGING A INNER JOIN SEACOLORSIZERUN_JOIN_MAT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND B.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;

-- Step 16.6 : China Color Size Run
--INITIAL
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH CHINACOLORSIZERUN_INIT AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, CHINA_COLOR_SIZE_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE CHINA_COLOR_SIZE_RUN IS NOT NULL 
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME, 
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID, 
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'China_Color_Size_Run__c' AS SF_FIELDNAME,  B.CHINA_COLOR_SIZE_RUN AS FIELDVALUE, 
18 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, MODIFIED_DATE,'N' 
FROM MAT_DELTA_SF_STAGING A INNER JOIN CHINACOLORSIZERUN_INIT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N');
COMMIT;

--DELTA
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING (
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS
)
WITH CHINACOLORSIZERUN AS
(
    SELECT DISTINCT MAGTEMPLATES_ID , ROW_ID, CHINA_COLOR_SIZE_RUN  FROM  TBL_RPT_MAT_REPORTING WHERE CHINA_COLOR_SIZE_RUN IS NOT NULL
)
,
CHINACOLORSIZERUN_JOIN_MAT AS
(
    SELECT M.MAGTEMPLATES_ID , M.ROW_ID, M.MODIFIED_DATE, S.CHINA_COLOR_SIZE_RUN  
    FROM MAT M INNER JOIN CHINACOLORSIZERUN S ON M.MAGTEMPLATES_ID = S.MAGTEMPLATES_ID AND M.ROW_ID = S.ROW_ID
    WHERE M.FIELDS_ID = 130
)
SELECT A.MAG_ID, A.MAG_NAME, A.MAGTEMPLATES_ID, A.MAGTEMPLATES_NAME,
A.ROW_ID, A.BRAND_ID, A.BRAND_NAME, A.SEASONS_ID,
A.SEASON_YEAR, A.SEASON_NAME, A.SEASON_SHORTNAME, 'China_Color_Size_Run__c' AS SF_FIELDNAME,  B.CHINA_COLOR_SIZE_RUN AS FIELDVALUE, 
18 AS SORT_ORDER, SEGMENT_COUNT, CREATE_DATE, B.MODIFIED_DATE,'N'
FROM MAT_DELTA_SF_STAGING A INNER JOIN CHINACOLORSIZERUN_JOIN_MAT B ON A.MAGTEMPLATES_ID = B.MAGTEMPLATES_ID AND A.ROW_ID = B.ROW_ID
WHERE A.SF_FIELDNAME = 'Planning_Choice__c'
AND A.SEASONS_ID IN (SELECT ID FROM SEASONS WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'Y')
AND B.MODIFIED_DATE > P_SF_LASTRUNDATETIME;
COMMIT;
-----------------------------------------------------------

--Step 17 : Format Dates to the correct format
--Step 17.1 : Update add dates with DD-MON-YY to YYYY-MM-DD HH:MI:SS
update mat_delta_sf_staging
set fieldvalue = TO_CHAR(TO_DATE(fieldvalue,'DD-MON-YY'), 'YYYY-MM-DD')
where length(fieldvalue) <= 9
and regexp_count(fieldvalue,'-') = 2;
COMMIT;
--
--Step 17.2 : Update all dates to be in the correct format for Salesforce (MM-DD-YYY HH:MM:SS)
UPDATE mat_delta_sf_staging a
set a.fieldvalue = TO_CHAR(TO_DATE(a.fieldvalue,'MM/DD/YYYY, HH:MI:SS AM'), 'YYYY-MM-DD')
where a.id in (select b.id from mat_delta_sf_staging b
inner join mat_delta_sf_fields c on b.sf_fieldname = c.salesforce_name and c.text_date = 'Y'
and a.fieldvalue is not null and (instr(substr(a.fieldvalue,1,4),'-') <> 0 or instr(substr(a.fieldvalue,1,4),'/') <> 0));
COMMIT;

-- Update all ROW_IDs + 1 to take into account the header record.
--UPDATE mat_delta_sf_staging
--SET ROW_ID = ROW_ID + 1;
--COMMIT;

--Step 18 : Move all staging records to the staging_bkp table.
INSERT /*+ append  */ INTO MAT_DELTA_SF_STAGING_BKP ( ID,
  MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS,BACKUP_DATE)
SELECT ID, MAG_ID,  MAG_NAME,  MAGTEMPLATES_ID,  MAGTEMPLATES_NAME,
  ROW_ID,  BRAND_ID,  BRAND_NAME,  SEASONS_ID,
  SEASON_YEAR,  SEASON_NAME, SEASON_SHORTNAME, SF_FIELDNAME,FIELDVALUE,SORT_ORDER,SEGMENT_COUNT,CREATE_DATE,MODIFIED_DATE,
  STATUS,SYSDATE
FROM MAT_DELTA_SF_STAGING;
COMMIT;

--Step 19 : After an inital load update SEASONS.INITIAL_DATA_LOADED from 'N' to 'Y'.
UPDATE SEASONS SET INITIAL_DATA_LOADED = 'Y' WHERE TRACK_DELTA = 'Y' AND INITIAL_DATA_LOADED = 'N';
COMMIT;

--Step 20 : Retrieve the total records count from the staging table.
SELECT COUNT(*) INTO P_SF_STAGING_COUNT FROM MAT_DELTA_SF_STAGING;

--Step 21 : Insert a record into the runlog with information regarding this run.
INSERT INTO MAT_DELTA_SF_RUNLOG (RUNTIME, RECORDS)
SELECT SYSDATE, P_SF_STAGING_COUNT FROM DUAL;
COMMIT;

END SP_SALESFORCEDELTA;