CREATE OR REPLACE PROCEDURE SP_SF_THIRD_PARTY AS 
BEGIN

EXECUTE IMMEDIATE 'TRUNCATE TABLE MAT_DELTA_SF_THIRD_PARTY';
COMMIT;

INSERT /*+ append  */ INTO MAT_DELTA_SF_THIRD_PARTY
(
  ARTICLE, SUBBRAND, SUBBRAND_DESCR, PRODUCT_HIERARCHY, PRODUCT_SHORT_DESC, LEVEL1,
  LEVEL1_KNOWN_AS, LEVEL1_DESC, LEVEL2, LEVEL2_KNOWN_AS, LEVEL2_DESC, LEVEL3,
  LEVEL3_KNOWN_AS, LEVEL3_DESC, SIZE_US, COLLECTION, GROSS_WEIGHT, NET_WEIGHT, MARKET_PLACE, STYLE_LIFECYCLE
)
SELECT LTRIM(MARA.MATNR,'0') ARTICLE, TO_CHAR(SUBRAND.ZZ_SUBRAND1) SUBRAND, TO_CHAR(SUBRAND.DESCR) SUBRAND_DESCR, 
       MARA.PRDHA PRODUCT_HIERARCHY, 
       MAMT.MAKTM PRODUCT_SHORT_DESC, TO_CHAR(HIER.ZZ_SECTOR) LEVEL1,'SECTOR' LEVEL1_KNOWN_AS, 
       TO_CHAR(HIER.ZZ_SEC_DESC) LEVEL1_DESC, TO_CHAR(HIER.ZZ_CATEGORY) LEVEL2,'CATEGORY' LEVEL2_KNOWN_AS, 
       TO_CHAR(HIER.ZZ_CAT_DESC) LEVEL2_DESC, MARA.MATKL LEVEL3,'CLASS' LEVEL3_KNOWN_AS, 
       TO_CHAR(HIER.ZZ_CLASS_DESC) LEVEL3_DESC, TO_CHAR(SZE.ZZ_SIZE1||SZE.ZZ_SIZE2) SIZE_US, ARTMAS.ZZ_COLLECT COLLECTION, 
       MARA.BRGEW  GROSS_WEIGHT,
       MARA.NTGEW NET_WEIGHT,CASE WHEN  MARKET.ATWRT = '0001' THEN 'YES' ELSE 'NO' END MARKET_PLACE,
       STYLE_LIFECYCLE.ATWRT STYLE_LIFECYCLE
FROM   MPA_MASTER.SAP_MARA MARA
       INNER JOIN   MPA_MASTER.SAP_MAMT MAMT ON MARA.ZZ_STYLE = MAMT.MATNR AND MAMT.SPRAS = 'E'
       LEFT JOIN MPA_MASTER.SAP_AUSP MARKET ON MARKET.OBJEK = MARA.MATNR AND MARKET.ATINN = 'MARKETPLACE'
       LEFT JOIN MPA_MASTER.SAP_AUSP STYLE_LIFECYCLE ON STYLE_LIFECYCLE.OBJEK = MARA.MATNR AND STYLE_LIFECYCLE.ATINN = 'STYLE_LIFECYCLE'
       LEFT JOIN MPA_MASTER.SAP_ZMD_HIERARCHY HIER ON MARA.ZZ_SUBCLASS1 = HIER.ZZ_SUBCLASS
       LEFT JOIN MPA_MASTER.SAP_ZZARTMAS ARTMAS ON MARA.MATNR = ARTMAS.MATNR 
       LEFT JOIN MPA_MASTER.SAP_AUSP AUSP ON MARA.MATNR = AUSP.OBJEK_TRIM AND AUSP.ATINN = 'SIZE' AND AUSP.KLART = '026'
       LEFT JOIN MPA_MASTER.SAP_ZZLBISIZE SZE ON AUSP.ATWRT = SZE.ZZ_SIZE
       LEFT JOIN MPA_MASTER.SAP_ZZSUBRANDT1  SUBRAND ON MARA.ZZ_SUBRAND1 = SUBRAND.ZZ_SUBRAND1
       LEFT JOIN MPA_MASTER.SAP_ZZLBICOLOR COLOR ON MARA.ZZ_CHOICE = COLOR.ZZ_COLOR  -- DO WE NEED SAP_ZZLBICOLORFRAG instead?
       LEFT JOIN MPA_MASTER.SAP_ZZSUBCLASS1 SUBCLASS ON MARA.ZZ_SUBCLASS1 = SUBCLASS.ZZ_SUBCLASS1
       LEFT JOIN MPA_MASTER.SAP_ZZMASTERSTYLET1 MASTERSTYLE ON TRIM(ARTMAS.ZZ_PTRNFMLY) = MASTERSTYLE.ZZ_PTRNFMLY
WHERE  MARA.MATNR IN (  SELECT  TRIM(OBJEK)
                        FROM    MPA_MAT.MAT_DELTA_SF_STAGING STAGING
                        INNER JOIN MPA_MASTER.SAP_MARA EXP ON STAGING.FIELDVALUE = TRIM(EXP.ZZ_CHOICEID) AND STAGING.SF_FIELDNAME = 'Planning_Choice__c' 
                        INNER JOIN MPA_MASTER.SAP_AUSP AUSP ON AUSP.OBJEK = EXP.MATNR AND AUSP.KLART = 'Z01' AND AUSP.ATINN = 'MARKETPLACE'
                        INNER JOIN MPA_MASTER.SAP_CABN CAB ON AUSP.ATINN = CAB.ATNAM
                        INNER JOIN  MPA_MASTER.SAP_CAWN CAWN ON CAWN.ATINN = CAB.ATINN AND LPAD(AUSP.ATZHL,4,'0') = CAWN.ATZHL
                        INNER JOIN MPA_MASTER.SAP_CAWNT CAWNT ON CAWN.ATINN = CAWNT.ATINN AND CAWN.ATZHL = CAWNT.ATZHL);
COMMIT;
END SP_SF_THIRD_PARTY;