WITH ALLOWEDATTRIBUTES AS
(
    SELECT  TRIM(OBJEK) OBJEK,AUSP.ATINN,CAWNT.ATWTB ATTRIBUTE_VALUE,AUSP.KLART FROM
    MPA_MAT.MAT_DELTA_SF_STAGING STAGING
    INNER JOIN MPA_MASTER.SAP_MARA EXP ON STAGING.FIELDVALUE = EXP.ZZ_CHOICEID AND STAGING.SF_FIELDNAME = 'Planning_Choice__c' AND STAGING.FIELDVALUE = '1116232654A2'
    INNER JOIN MPA_MASTER.SAP_AUSP AUSP ON AUSP.OBJEK = EXP.MATNR AND AUSP.KLART = '026' AND AUSP.ATINN IN ('COLORAPP','PACKAGING','SIZE') -- Check with Muthu D
    INNER JOIN MPA_MASTER.SAP_CABN CAB ON AUSP.ATINN = CAB.ATNAM
    INNER JOIN  MPA_MASTER.SAP_CAWN CAWN ON CAWN.ATINN = CAB.ATINN AND LPAD(AUSP.ATZHL,4,'0') = CAWN.ATZHL
    INNER JOIN MPA_MASTER.SAP_CAWNT CAWNT ON CAWN.ATINN = CAWNT.ATINN AND CAWN.ATZHL = CAWNT.ATZHL
),
HTS_CODE AS
(
    SELECT  ESTMJ.MATNR,AUSP.ATWRT ATTRIBUTE_VALUE FROM
    MPA_MASTER.SAP_ESTMJ ESTMJ
    INNER JOIN MPA_MASTER.SAP_MARA SKULIST ON  ESTMJ.MATNR = SKULIST.MATNR
    INNER JOIN MPA_MAT.MAT_DELTA_SF_STAGING STAGING ON STAGING.FIELDVALUE = SKULIST.ZZ_CHOICEID AND STAGING.SF_FIELDNAME = 'Planning_Choice__c' AND STAGING.FIELDVALUE = '1116232654A2'
    INNER JOIN MPA_MASTER.SAP_ESTVH ESTVH ON ESTMJ.RECNROOT = ESTVH.RECNROOT AND ESTVH.NAMEMST = 'ZL_COMC_DUTY_DATA'
    INNER JOIN MPA_MASTER.SAP_ESTVA ESTVA ON ESTVH.RECN = ESTVA.RECNTVH  
    INNER JOIN MPA_MASTER.SAP_AUSP_EHS AUSP ON AUSP.OBJEK = ESTVA.RECN || ESTVA.ACTN AND AUSP.ATINN = 'ZSL_COMC_HTS'
    INNER JOIN MPA_MASTER.SAP_ESTDU ESTDU ON ESTVA.RECN = ESTDU.RECNMST AND ESTDU.RVLID = 'US'
),
ALCOHOL  AS
(
    SELECT ESTMJ.MATNR, ESTVP.COMPAVG || NVL(COMPEXP,'%')  ATTRIBUTE_VALUE FROM
    MPA_MASTER.SAP_ESTMJ ESTMJ
    INNER JOIN  MPA_MASTER.SAP_MARA SKULIST ON  ESTMJ.MATNR = SKULIST.MATNR
    INNER JOIN MPA_MAT.MAT_DELTA_SF_STAGING STAGING ON STAGING.FIELDVALUE = SKULIST.ZZ_CHOICEID AND STAGING.SF_FIELDNAME = 'Planning_Choice__c' AND STAGING.FIELDVALUE = '1116232654A2'
    INNER JOIN MPA_MASTER.SAP_ESTVP ESTVP ON ESTMJ.RECNROOT = ESTVP.RECNROOT
    INNER JOIN MPA_MASTER.SAP_ESTRI ESTRI ON ESTRI.RECNROOT = ESTVP.RECNCMP AND ESTRI.IDCAT = 'CAS' AND ESTRI.IDENT = '64-17-5' AND ESTVP.COMPCAT = 'ACT_AGENT'
),
COMPOSITION AS
(
    SELECT ESTMJ.MATNR, ESTRI.IDENT ATTRIBUTE_VALUE FROM
    MPA_MASTER.SAP_ESTMJ ESTMJ
    INNER JOIN  MPA_MASTER.SAP_MARA SKULIST ON  ESTMJ.MATNR = SKULIST.MATNR
    INNER JOIN MPA_MAT.MAT_DELTA_SF_STAGING STAGING ON STAGING.FIELDVALUE = SKULIST.ZZ_CHOICEID AND STAGING.SF_FIELDNAME = 'Planning_Choice__c'  AND STAGING.FIELDVALUE = '1116232654A2'
    INNER JOIN MPA_MASTER.SAP_ESTRI ESTRI ON ESTRI.RECNROOT = ESTMJ.RECNROOT AND ESTRI.IDCAT = 'Z_CID'
)
SELECT  /*+ FULL(TMP_EXPORT) FULL(MARA) PARALLEL(16)*/
MARA.MATNR ARTICLE,MARA.SATNR STYLE,TO_CHAR(SZE.ZZ_SIZE1||SZE.ZZ_SIZE2) SIZE_US, MEAN.EAN11 BARCODE,
MAKT.MAKTX PRODUCT_MAIN_DESC,  MAMT.MAKTM PRODUCT_SHORT_DESC,
TO_CHAR(HIER.ZZ_SECTOR) LEVEL1,'SECTOR' LEVEL1_KNOWN_AS, TO_CHAR(HIER.ZZ_SEC_DESC) LEVEL1_DESC,
TO_CHAR(HIER.ZZ_CATEGORY) LEVEL2,'CATEGORY' LEVEL2_KNOWN_AS, TO_CHAR(HIER.ZZ_CAT_DESC) LEVEL2_DESC,
MARA.MATKL LEVEL3,'CLASS' LEVEL3_KNOWN_AS, TO_CHAR(HIER.ZZ_CLASS_DESC) LEVEL3_DESC,
NULL LEVEL4,NULL LEVEL4_KNOWN_AS, NULL LEVEL4_DESC,
NULL LEVEL5,NULL LEVEL5_KNOWN_AS, NULL LEVEL5_DESC,
NULL LEVEL6,NULL LEVEL6_KNOWN_AS, NULL LEVEL6_DESC,
ARTMAS.ZZ_COLLECT STORY,MARA.ZZ_SUBCLASS1 ZZ_SUBCLASS,TO_CHAR(SUBCLASS.DESCR) SUBCLASS_DESCR,MAKT.MAKTX STYLE_DESCRIPTION,
MARA.PRDHA PRODUCT_HIERARCHY,TO_CHAR(SZE.ZZ_SIZE1||SZE.ZZ_SIZE2) SIZE_DESCRIPTION, TO_CHAR(SUBCLASSGRP.ZZ_SUBCLASSGRP1) SILHOUETTE,
MARA.ZZ_CHOICEID MERCH_PLAN_ID, MARA.ZZ_SUBRAND1 SUBBRAND,SUBBRAND.DESCR SUBBRAND_DESCRIPTION, ARTMAS.ZZ_BESTWIN EMOTIONAL_SPACE,
ARTMAS.ZZ_FABFAM FABRIC_FAMILY, ARTMAS.ZZ_PLCYCLE PRODUCT_LIFECYCLE, ARTMAS.ZZ_PTRNFMLY MASTER_STYLE,MASTERSTYLE.DESCR MASTER_STYLE_DESCRIPTION
,LININGLEVEL.ATTRIBUTE_VALUE LINING_LEVEL,STRUCTURE.ATTRIBUTE_VALUE STRUCTURE,BACK_TYPE.ATTRIBUTE_VALUE BACK_TYPE, CATEGORY.ATTRIBUTE_VALUE CATEGORY,
SUB_CATEGORY.ATTRIBUTE_VALUE    SUB_CATEGORY,
SILHOUETTE_FORM.ATTRIBUTE_VALUE    SILHOUETTE_FORM,
VSBA_BRAND.ATTRIBUTE_VALUE    VSBA_BRAND,
VSBA_SUB_BRAND.ATTRIBUTE_VALUE    VSBA_SUB_BRAND,
VSBA_STATUS.ATTRIBUTE_VALUE    VSBA_STATUS,
VSBA_LAUNCH_SEASON.ATTRIBUTE_VALUE    VSBA_LAUNCH_SEASON,
VSBA_PRODUCT_LIFECYCLE_BEAUTY.ATTRIBUTE_VALUE    VSBA_PRODUCT_LIFECYCLE_BEAUTY,
VSBA_MATERIALS.ATTRIBUTE_VALUE    VSBA_MATERIALS,
VSBA_MERCHANDISE_TIER.ATTRIBUTE_VALUE    VSBA_MERCHANDISE_TIER,
VSBA_SAP_CATEGORY_CODE.ATTRIBUTE_VALUE    VSBA_SAP_CATEGORY_CODE,
VSBA_SAP_SUB_CATEGORY_CODE.ATTRIBUTE_VALUE    VSBA_SAP_SUB_CATEGORY_CODE,
VSBA_SAP_SILHOUETTE_FORMCODE.ATTRIBUTE_VALUE    VSBA_SAP_SILHOUETTE_FORMCODE,
CASE WHEN MARA.GEWEI = 'KG' THEN TO_CHAR(MARA.BRGEW,'FM90.99') ELSE TO_CHAR(ROUND(MARA.BRGEW * 0.454545454545455,3),'FM90.99') END GROSS_WEIGHT,
'KG' GROSS_WEIGHT_UNIT, MARA.INHAL NET_CONTENTS, MARA.INHME CONTENT_UNIT,
MARA.PROFL DG_INDIGATOR_PROF, MARA.STOFF HAZ_MATERIAL_NUMBER, 'ML' DG_CONTENT_UNIT,
HTS.ATTRIBUTE_VALUE AS TARIFF_CODE_COUNTRY_1, NULL AS TARIFF_CODE_COUNTRY_2,
ALC.ATTRIBUTE_VALUE ALCOHOL_PERCENTAGE,CMP.ATTRIBUTE_VALUE COMPOSITION,INNERPK.UMREZ INNER_PACK,CASEPK.UMREZ CASE_PACK
,COLORFRAG.ZZ_ATBEZ COLOR_DESCRIPTION,AUSPEXT.ZVALUE GIFT_SET_CONTENTS
FROM
MPA_MAT.MAT_DELTA_SF_STAGING TMP_EXPORT
INNER JOIN MPA_MASTER.SAP_MARA MARA ON  TMP_EXPORT.FIELDVALUE = TRIM(MARA.ZZ_CHOICEID) AND TMP_EXPORT.SF_FIELDNAME = 'Planning_Choice__c'  AND TMP_EXPORT.FIELDVALUE = '1116232654A2'
AND MARA.MATNR IN
(
'000000000024589820',
'000000000024589821',
'000000000024589822'
)
LEFT JOIN MPA_MASTER.SAP_AUSP AUSP ON MARA.MATNR = AUSP.OBJEK_TRIM AND AUSP.ATINN = 'SIZE' AND KLART = '026'
LEFT JOIN MPA_MASTER.SAP_ZZLBISIZE SZE ON AUSP.ATWRT = SZE.ZZ_SIZE
LEFT JOIN MPA_MASTER.SAP_MEAN MEAN ON MARA.MATNR = MEAN.MATNR
INNER JOIN   MPA_MASTER.SAP_MAKT MAKT ON MARA.MATNR = MAKT.MATNR AND MAKT.SPRAS = 'E'
INNER JOIN   MPA_MASTER.SAP_MAMT MAMT ON MARA.ZZ_STYLE = MAMT.MATNR AND MAMT.SPRAS = 'E'
LEFT JOIN MPA_MASTER.SAP_ZMD_HIERARCHY HIER ON MARA.ZZ_SUBCLASS1 = HIER.ZZ_SUBCLASS
LEFT JOIN MPA_MASTER.SAP_ZZARTMAS ARTMAS ON MARA.MATNR = ARTMAS.MATNR
LEFT JOIN MPA_MASTER.SAP_ZZSUBCLASST1 SUBCLASS ON SUBCLASS.ZZ_SUBCLASS1 = MARA.ZZ_SUBCLASS1
LEFT JOIN MPA_MASTER.SAP_ZZSUBCLASS1 SUBCLASSGRP ON MARA.ZZ_SUBCLASS1 = SUBCLASSGRP.ZZ_SUBCLASS1
LEFT JOIN MPA_MASTER.SAP_ZZSUBRANDT1 SUBBRAND ON MARA.ZZ_SUBRAND1 = SUBBRAND.ZZ_SUBRAND1
LEFT JOIN MPA_MASTER.SAP_ZZMASTERSTYLET1 MASTERSTYLE ON TRIM(ARTMAS.ZZ_PTRNFMLY) = MASTERSTYLE.ZZ_PTRNFMLY
LEFT JOIN ALLOWEDATTRIBUTES LININGLEVEL ON LININGLEVEL.OBJEK = MARA.MATNR AND LININGLEVEL.ATINN = 'LININGLEVEL'
LEFT JOIN ALLOWEDATTRIBUTES STRUCTURE ON STRUCTURE.OBJEK = MARA.MATNR AND STRUCTURE.ATINN = 'STRUCTURE'
LEFT JOIN ALLOWEDATTRIBUTES BACK_TYPE ON BACK_TYPE.OBJEK = MARA.MATNR AND BACK_TYPE.ATINN = 'BACK_TYPE'
LEFT JOIN ALLOWEDATTRIBUTES CATEGORY ON CATEGORY.OBJEK = MARA.MATNR AND CATEGORY.ATINN = 'CATEGORY'
LEFT JOIN ALLOWEDATTRIBUTES SUB_CATEGORY ON SUB_CATEGORY.OBJEK = MARA.MATNR AND SUB_CATEGORY.ATINN = 'SUB_CATEGORY'
LEFT JOIN ALLOWEDATTRIBUTES SILHOUETTE_FORM ON SILHOUETTE_FORM.OBJEK = MARA.MATNR AND SILHOUETTE_FORM.ATINN = 'SILHOUETTE_FORM'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_BRAND ON VSBA_BRAND.OBJEK = MARA.MATNR AND VSBA_BRAND.ATINN = 'VSBA_BRAND'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_SUB_BRAND ON VSBA_SUB_BRAND.OBJEK = MARA.MATNR AND VSBA_SUB_BRAND.ATINN = 'VSBA_SUB_BRAND'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_STATUS ON VSBA_STATUS.OBJEK = MARA.MATNR AND VSBA_STATUS.ATINN = 'VSBA_STATUS'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_LAUNCH_SEASON ON VSBA_LAUNCH_SEASON.OBJEK = MARA.MATNR AND VSBA_LAUNCH_SEASON.ATINN = 'VSBA_LAUNCH_SEASON'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_PRODUCT_LIFECYCLE_BEAUTY ON VSBA_PRODUCT_LIFECYCLE_BEAUTY.OBJEK = MARA.MATNR AND VSBA_PRODUCT_LIFECYCLE_BEAUTY.ATINN = 'VSBA_PRODUCT_LIFECYCLE_BEAUTY'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_MATERIALS ON VSBA_MATERIALS.OBJEK = MARA.MATNR AND VSBA_MATERIALS.ATINN = 'VSBA_MATERIALS'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_MERCHANDISE_TIER ON VSBA_MERCHANDISE_TIER.OBJEK = MARA.MATNR AND VSBA_MERCHANDISE_TIER.ATINN = 'VSBA_MERCHANDISE_TIER'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_SAP_CATEGORY_CODE ON VSBA_SAP_CATEGORY_CODE.OBJEK = MARA.MATNR AND VSBA_SAP_CATEGORY_CODE.ATINN = 'VSBA_SAP_CATEGORY_CODE'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_SAP_SUB_CATEGORY_CODE ON VSBA_SAP_SUB_CATEGORY_CODE.OBJEK = MARA.MATNR AND VSBA_SAP_SUB_CATEGORY_CODE.ATINN = 'VSBA_SAP_SUB_CATEGORY_CODE'
LEFT JOIN ALLOWEDATTRIBUTES VSBA_SAP_SILHOUETTE_FORMCODE ON VSBA_SAP_SILHOUETTE_FORMCODE.OBJEK = MARA.MATNR AND VSBA_SAP_SILHOUETTE_FORMCODE.ATINN = 'VSBA_SAP_SILHOUETTE_FORMCODE'
LEFT JOIN HTS_CODE HTS ON HTS.MATNR = MARA.MATNR
LEFT JOIN ALCOHOL ALC ON ALC.MATNR = MARA.MATNR
LEFT JOIN COMPOSITION CMP ON CMP.MATNR = MARA.MATNR
LEFT JOIN MPA_MASTER.SAP_MARM INNERPK ON INNERPK.MATNR = MARA.MATNR AND INNERPK.MEINH = 'PKA'
LEFT JOIN MPA_MASTER.SAP_MARM CASEPK ON CASEPK.MATNR = MARA.MATNR AND CASEPK.MEINH = 'CV'
LEFT JOIN MPA_MASTER.SAP_ZZLBICOLORFRAG COLORFRAG ON MARA.ZZ_CHOICE = COLORFRAG.ZZ_CHOICE
LEFT JOIN MPA_MASTER.SAP_ZZAUSPEXT AUSPEXT ON MARA.MATNR = AUSPEXT.MATNR AND AUSPEXT.ATNAM = 'GIFT_SET_CONTENTS';
