create or replace PROCEDURE           "SP_SF_THIRD_PARTY" AS 

    -- Variable that holds the count of total records for this run. Used in the MAT_DELTA_SF_RUNLOG Table.
    P_SF_STAGING_COUNT NUMBER;
    -- Variable that holds last runtime from the MAT_DELTA_SF_RUNLOG Table.
    P_SF_LASTRUNDATETIME DATE;

BEGIN

-- Retrieve the last runtime from the runlog.
SELECT RUNTIME INTO P_SF_LASTRUNDATETIME FROM "MAT_DELTA_SF_3RDParty_RUNLOG" WHERE ID IN (SELECT MAX(ID) FROM "MAT_DELTA_SF_3RDParty_RUNLOG");

EXECUTE IMMEDIATE 'TRUNCATE TABLE MAT_DELTA_SF_THIRD_PARTY';
COMMIT;

INSERT /*+ append  */ INTO MAT_DELTA_SF_THIRD_PARTY
(
  ARTICLE, SUBBRAND, SUBBRAND_DESCR, PRODUCT_HIERARCHY, PRODUCT_SHORT_DESC, LEVEL1,
  LEVEL1_DESC, LEVEL2, LEVEL2_DESC, LEVEL3,
  LEVEL3_DESC, SIZE_US, COLLECTION, GROSS_WEIGHT, NET_WEIGHT, MARKET_PLACE, STYLE_LIFECYCLE,
  PRODUCT_LIFECYCLE,FABRIC_FAMILY,CHOICE_FAMILY,
  VSS_PLAN_ORG,MASTERSTYLE,LINING_LEVEL,TICKET_PRICE,TREATMENT,COVERAGE,STRUCTURE,GRAPHIC,NAME,COLOR_MARKETING,SUBCLASS_NAME,GENERIC_DESC,GENERIC_NUMBER,PRICE_POINT, VENDOR_GTIN
  ,PRIMARY_PROD_OFFICE
)
WITH ARTICLES AS 
(
    SELECT /*+MATERIALIZE */ MATNR FROM MPA_MASTER.SAP_MARA MARA 
    INNER JOIN MPA_MASTER.SAP_AUSP AUSP ON AUSP.OBJEK = MARA.MATNR AND AUSP.ATINN = 'MARKETPLACE' AND AUSP.ATWRT = '0001'
    WHERE (MARA.LAST_UPDATE_TS > P_SF_LASTRUNDATETIME OR AUSP.LAST_UPDATE_TS > P_SF_LASTRUNDATETIME)
),
ATTRIBUTES AS
(
SELECT AUSP.OBJEK,CAB.ATNAM AS ATTRIBUTE_NAME, CAWNT.ATWTB AS ATTRIBUTE_VALUE
FROM   ARTICLES EXP  
INNER JOIN MPA_MASTER.SAP_AUSP AUSP ON AUSP.OBJEK = EXP.MATNR
INNER JOIN MPA_MASTER.SAP_CABN CAB ON AUSP.ATINN = CAB.ATNAM  AND  CAB.ATNAM in ('LININGLEVEL','PRICEPOINT','TICKET','TREATMENT','COVERAGE_CH','STRUCTURE_CH','GRAPHIC_CH')
INNER JOIN  MPA_MASTER.SAP_CAWN CAWN ON CAWN.ATINN = CAB.ATINN AND LPAD(AUSP.ATZHL,4,'0') = CAWN.ATZHL
INNER JOIN MPA_MASTER.SAP_CAWNT CAWNT ON CAWN.ATINN = CAWNT.ATINN AND CAWN.ATZHL = CAWNT.ATZHL
) 
SELECT LTRIM(MARA.MATNR,'0') ARTICLE__c, TO_CHAR(SUBRAND.ZZ_SUBRAND1) SUBRAND__c, TO_CHAR(SUBRAND.DESCR) SUBRAND_DESCR__c, 
       MARA.PRDHA PRODUCT_HIERARCHY__c, 
       MAMT.MAKTM PRODUCT_SHORT_DESC__c, TO_CHAR(HIER.ZZ_SECTOR) Sector_Code__c, 
       TO_CHAR(HIER.ZZ_SEC_DESC) Sector__c, TO_CHAR(HIER.ZZ_CATEGORY) Category_Code__c, 
       TO_CHAR(HIER.ZZ_CAT_DESC) Category__c, MARA.MATKL Class_Code__c,
       TO_CHAR(HIER.ZZ_CLASS_DESC) Class__c, TO_CHAR(SZE.ZZ_SIZE1||SZE.ZZ_SIZE2) SIZE_US__c, ARTMAS.ZZ_COLLECT COLLECTION__c, 
       MARA.BRGEW  GROSS_WEIGHT__c,
       MARA.NTGEW NET_WEIGHT,CASE WHEN  MARKET.ATWRT = '0001' THEN 'YES' ELSE 'NO' END MARKET_PLACE__c,
       STYLE_LIFECYCLE.ATWRT STYLE_LIFECYCLE__c, 
       ARTMAS.zz_plcycle Product_Lifecycle__c,
       ARTMAS.zz_fabfam Fabric_Family__c,
       ARTMAS.zz_colfam Choice_Family__c,
       ARTMAS.zz_planorg1 VSS_Plan_Org__c,
       ARTMAS.zz_ptrnfmly Masterstyle__c,
       LININGLEVEL.ATTRIBUTE_VALUE LINING_LEVEL__c,
       PM.KBETR TICKET_Price__c,
       TREATMENT.ATTRIBUTE_VALUE TREATMENT__c,
       COVERAGE.ATTRIBUTE_VALUE COVERAGE__c,
       STRUCTURE.ATTRIBUTE_VALUE STRUCTURE__c,
       GRAPHIC.ATTRIBUTE_VALUE GRAPHIC__c,
       LTRIM(MARA.MATNR,'0') NAME__c,
       --mUTHU ADDED THE following FROM HERE
       ARTMAS.ZZ_CMNAME Flex_Color_Marketing_Name__c,
       TO_CHAR(HIER.ZZ_SUBCLASS_DESC) Sub_Class__c,
       STYLE_MAKT.MAKTX Generic_Description__c,
       MARA.ZZ_STYLE Generic_number,
       PRICEPOINT.ATTRIBUTE_VALUE Price_Point_c,
       MARA.EAN11 GTIN,
       ARTMAS.ZZ_PRMPOFFIC
FROM  ARTICLES ART
INNER JOIN MPA_MASTER.SAP_MARA MARA ON ART.MATNR = MARA.MATNR
       INNER JOIN   MPA_MASTER.SAP_MAMT MAMT ON MARA.ZZ_STYLE = MAMT.MATNR AND MAMT.SPRAS = 'E'
       LEFT JOIN   ATTRIBUTES LININGLEVEL ON LININGLEVEL.OBJEK = MARA.MATNR AND LININGLEVEL.ATTRIBUTE_NAME = 'LININGLEVEL'
       LEFT JOIN   ATTRIBUTES PRICEPOINT ON PRICEPOINT.OBJEK = MARA.MATNR  AND PRICEPOINT.ATTRIBUTE_NAME = 'PRICEPOINT'
       LEFT JOIN   ATTRIBUTES TICKET ON TICKET.OBJEK = MARA.MATNR  AND TICKET.ATTRIBUTE_NAME = 'TICKET'
       LEFT JOIN   ATTRIBUTES TREATMENT ON TREATMENT.OBJEK = MARA.MATNR  AND TREATMENT.ATTRIBUTE_NAME = 'TREATMENT'
       LEFT JOIN   ATTRIBUTES COVERAGE ON COVERAGE.OBJEK = MARA.MATNR  AND COVERAGE.ATTRIBUTE_NAME = 'COVERAGE_CH'
       LEFT JOIN   ATTRIBUTES STRUCTURE ON STRUCTURE.OBJEK = MARA.MATNR  AND STRUCTURE.ATTRIBUTE_NAME = 'STRUCTURE_CH'
       LEFT JOIN   ATTRIBUTES GRAPHIC ON GRAPHIC.OBJEK = MARA.MATNR  AND GRAPHIC.ATTRIBUTE_NAME = 'GRAPHIC_CH'              
       LEFT JOIN MPA_MASTER.SAP_AUSP MARKET ON MARKET.OBJEK = MARA.MATNR AND MARKET.ATINN = 'MARKETPLACE'
       LEFT JOIN MPA_MASTER.SAP_AUSP STYLE_LIFECYCLE ON STYLE_LIFECYCLE.OBJEK = MARA.MATNR AND STYLE_LIFECYCLE.ATINN = 'STYLE_LIFECYCLE'
       LEFT JOIN MPA_MASTER.SAP_ZMD_HIERARCHY HIER ON MARA.ZZ_SUBCLASS1 = HIER.ZZ_SUBCLASS
       LEFT JOIN MPA_MASTER.SAP_ZZARTMAS ARTMAS ON MARA.MATNR = ARTMAS.MATNR 
       LEFT JOIN MPA_MASTER.SAP_AUSP AUSP ON MARA.MATNR = AUSP.OBJEK_TRIM AND AUSP.ATINN = 'SIZE' AND AUSP.KLART = '026'
       LEFT JOIN MPA_MASTER.SAP_ZZLBISIZE SZE ON AUSP.ATWRT = SZE.ZZ_SIZE
       LEFT JOIN MPA_MASTER.SAP_ZZSUBRANDT1  SUBRAND ON MARA.ZZ_SUBRAND1 = SUBRAND.ZZ_SUBRAND1
       LEFT JOIN MPA_MASTER.SAP_ZZLBICOLOR COLOR ON MARA.ZZ_CHOICE = COLOR.ZZ_COLOR
       LEFT JOIN MPA_MASTER.SAP_ZZSUBCLASS1 SUBCLASS ON MARA.ZZ_SUBCLASS1 = SUBCLASS.ZZ_SUBCLASS1
       LEFT JOIN MPA_MASTER.SAP_ZZMASTERSTYLET1 MASTERSTYLE ON TRIM(ARTMAS.ZZ_PTRNFMLY) = MASTERSTYLE.ZZ_PTRNFMLY
       LEFT JOIN MPA_MASTER.SAP_ZZLBICOLOR COLOR ON MARA.ZZ_CHOICE = COLOR.ZZ_COLOR
       INNER JOIN MPA_MASTER.SAP_MAKT STYLE_MAKT ON MARA.ZZ_STYLE = STYLE_MAKT.MATNR AND STYLE_MAKT.SPRAS='E' AND MARA.ATTYP <> '01'     
       LEFT JOIN  MPA_MASTER.SAP_PRICEMASTER PM ON PM.ARTICLE = MARA.MATNR AND VKORG = '1108' AND STATUS = 'A'
       ;
COMMIT;

SELECT COUNT(*) INTO P_SF_STAGING_COUNT FROM MAT_DELTA_SF_THIRD_PARTY;

--Insert a record into the 3rd party runlog with information regarding this run.
INSERT INTO "MAT_DELTA_SF_3RDParty_RUNLOG" (RUNTIME, RECORDS)
SELECT SYSDATE, P_SF_STAGING_COUNT FROM DUAL;
COMMIT;

END SP_SF_THIRD_PARTY;